language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

r_binary_packages:
  - reshape2
  - evaluate
  - stringr
  - stringi
  - devtools
  - testthat
  - ggplot2
  - png
  - Rcpp
  - RcppArmadillo
  - RcppProgress
  - dplyr
  - dbscan
  - knitr
  - rmarkdown

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11

#r_github_packages:
#  - yihui/knitr
#  - rstudio/rmarkdown
#  - jimhester/knitrBootstrap
#  - kevinushey/rex
#  - gaborcsardi/crayon
#  - jimhester/covr
#  - gagolews/stringi

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: axy148@miami.edu
    on_failure: axy148@miami.edu


env:
  global:
    - _R_CHECK_TIMINGS_="0"