language: r

r: bioc-devel
warnings_are_errors: false
sudo: false
cache: packages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

#r_binary_packages:
#  - stringi

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11 -fPIC

r_github_packages:
#  - gagolews/stringi
  - yihui/knitr
  - rstudio/rmarkdown
  - jimhester/knitrBootstrap
  - kevinushey/rex
  - gaborcsardi/crayon
  - jimhester/covr

script:
  - |
    R CMD build .
    travis_wait 40 R CMD check PathwaySplice*tar.gz
  
r_build_args: --no-manual --no-resave-data
r_check_args: --no-vignettes --no-manual

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: axy148@miami.edu
    on_failure: axy148@miami.edu


env:
  global:
    - _R_CHECK_TIMINGS_="0"