language: r
r:
  - bioc-devel

cache: packages
warnings_are_errors: true
sudo: false 
bioc_required: true
bioc_use_devel: true

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

before_install: |
  mkdir ~/.R
  cat <<EOF > ~/.R/Makevars
  CXX1X=g++-4.9
  CXX1XSTD=-std=c++11
  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"

r_packages:
    - knitr
    - rmarkdown
    - gdata
    - igraph

bioc_packages:
     - org.Hs.eg.db
     - geneLenDataBase
     - GO.db
     - goseq
     - JunctionSeq
     
##     - DOSE
##     - GOSemSim

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(PathwaySplice);data(mds);re<-LRtestBias(mds)'

notifications:
  email:
    recipients: axy148@miami.edu
    on_success: always
    on_failure: always