---
title: "PathwaySplice"
author: "Aimin Yan"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{PathwaySplice}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r, echo = FALSE}
knitr::opts_chunk$set(fig.width=12,fig.height=8,collapse = FALSE, comment = "#>")
```

# Use PathwaySplice

+ Convert feature based data to gene based data
```{r eval=TRUE,warning=FALSE,message=FALSE,results='hide'}
library(PathwaySplice)
data("featureBasedData")
res2 <- makeGeneTable(featureBasedData)
```

+ Apply logistic regression model to identify bias factor
```{r eval=TRUE,warning=FALSE,message=FALSE,results='hide'}
res2 <- makeGeneTable(featureBasedData)
res3 <- lrTestBias(res2,loc.x=2,loc.y=150,y.lim=200,boxplot.width=0.3)
#loc.x and loc.y indicates location of p-value
```

+ Perform analysis using pathwaysplice
```{r eval=TRUE,warning=FALSE,message=FALSE,results='hide'}

# This function performes gene set analysis that adjusts for different number of gene subfeatures 
# (i.e. exons, spicing junctions, or gene length indicated by *adjust*) associated with each gene. 
# The significant genes are those with perGeneQvalue (from DEXSeq) < *threshold*.
res2 <- makeGeneTable(featureBasedData)
res4 <- runPathwaySplice(res2,genome='hg19',id='ensGene',test.cats=c('GO:BP'),go.size.cut=c(5,30),method='Wallenius')
```

+ Build up network based on the overlap between gene sets and visualize this network

```{r eval=TRUE,warning=FALSE,message=FALSE,results='hide'}
#GO
# similarity.threshold: Gene sets with Jaccard coefficient > similarity threshold are connected by a line,
# with thickness proportional to Jaccard coefficient

dir.name <- tempdir() # give output
output.file.dir <- file.path(dir.name,"OutputEnmap")
res2 <- makeGeneTable(featureBasedData)
res4 <- runPathwaySplice(res2,genome='hg19',id='ensGene',test.cats=c('GO:BP'),go.size.cut=c(5,30),method='Wallenius')
enmap <- enrichmentMap(res4,n=3,output.file.dir
                       =output.file.dir,similarity.threshold=0)
```