# installed.packages()
# install.packages("RCurl")
# source("http://bioconductor.org/biocLite.R")
# source("https://bioconductor.org/biocLite.R")
# biocLite("biomaRt")
# library(biomaRt)
# install.packages("roxygen2")
# library(roxygen2)
# biocLite("JunctionSeq")
# library(JunctionSeq)
# biocLite("goseq")
# library(goseq)
# biocLite("org.Mm.eg.db")
# library(org.Mm.eg.db)
# biocLite("org.Hs.eg.db")
# library(org.Hs.eg.db)

# require(GO.db)
# biocLite("geneLenDataBase")
# install.packages("geneLenDataBase")
# require(geneLenDataBase)
# install.packages("GSA")
# library(GSA)
# install.packages("VennDiagram")
# library(VennDiagram)
# install.packages("openssl")
# biocLite("cummeRbund")
# library(cummeRbund)
# install.packages("popbio")
# library(popbio)
# source("https://bioconductor.org/biocLite.R")
# biocLite("affycoretools")
# library(affycoretools)
# source("https://bioconductor.org/biocLite.R")
# biocLite("ReportingTools")
# library(ReportingTools)
# biocLite("hgu95av2.db")
# install.packages("devtools")
# library(devtools)
# install.packages("rgl")
# library(rgl)
# install.packages("rgl")
# install.packages("qpcR")


# gene.model<-read.table("/media/H_driver/Annotation/mm10/genes_table_02052016.csv",header = TRUE, sep = ",", as.is=TRUE)
# save(gene.model,file="~/GOSJ/data/gene.model.RData")

# gene.model.hg38<-read.table("/media/H_driver/Annotation/hg38/genes_table_02092016.csv",header = TRUE, sep = ",", as.is=TRUE)
# save(gene.model.hg38,file="~/GOSJ/data/gene.model.hg38.RData")

