InstallOtherPackage <- function() {

  #installed.packages()
  install.packages("RCurl")
  install.packages("roxygen2")
  source("http://bioconductor.org/biocLite.R")

  biocLite("org.Mm.eg.db")
  biocLite("DEXSeq")
  biocLite("biomaRt")
  biocLite("JunctionSeq")
  biocLite("goseq")
  biocLite("org.Hs.eg.db")
  biocLite("geneLenDataBase")

  install.packages("GSA")
  install.packages("VennDiagram")
  install.packages("openssl")
  biocLite("cummeRbund")
  install.packages("popbio")
  biocLite("affycoretools")
  biocLite("ReportingTools")
  biocLite("hgu95av2.db")
  install.packages("devtools")
  install.packages("rgl")
  install.packages("qpcR")
  biocLite("ggbio")
  biocLite("clusterProfiler")
  biocLite("AnnotationHub")
  biocLite("Homo.sapiens")
  biocLite("TxDb.Hsapiens.UCSC.hg19.knownGene")
  biocLite("BSgenome.Hsapiens.UCSC.hg19")
  biocLite("biomaRt")
  biocLite("TxDb.Athaliana.BioMart.plantsmart22")
  biocLite("OrderedList")
  biocLite("Rgraphviz")

  #loading
  library(DEXSeq)
  library(biomaRt)
  library(roxygen2)
  library(JunctionSeq)
  library(goseq)
  library(org.Mm.eg.db)
  library(org.Hs.eg.db)
  library(GO.db)
  library(geneLenDataBase)
  library(GSA)
  library(VennDiagram)
  library(cummeRbund)
  library(popbio)
  library(affycoretools)
  library(ReportingTools)
  library("hgu95av2.db")
  library(devtools)
  library(rgl)
  library(qpcR)
  library(clusterProfiler)
  library(OrderedList)
  library(Rgraphviz)

}
